name: No Response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly. `workflow_dispatch` is optional.
on:
  workflow_dispatch:
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after 2am, every Sunday
    - cron: '5 2 * * 0'

permissions:
  issues: write

jobs:
  noResponse:
    name: No Response Check
    runs-on: ubuntu-latest
    steps:
      - uses: bugwelle/no-response-action@main
        with:
          daysUntilClose: 0
          closeComment: |
            This issue has been automatically closed because there has been no response to our request for more information.
            Please reach out if you have the answers we need, so that we can investigate further.
